sudo: false
language: php
cache:
  directories:
  - vendor
  - $HOME/.composer/cache
matrix:
  include:
  - php: 7.1
    env: PHPLINT=1 COVERAGE=1
  - php: 7.0
  allow_failures:
  - php: nightly
before_script:
- composer self-update
- composer install
script:
- |
  if [[ "$PHPLINT" == "1" ]]; then
    find -L .  -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  fi
- |
  if [[ -z "$CODECLIMATE_REPO_TOKEN" ]]; then
    COVERAGE="0"
  fi
- |
  if [[ "$COVERAGE" == "1" ]]; then
    mkdir -p build/logs
    vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
    vendor/bin/test-reporter;
  else
    vendor/bin/phpunit -c phpunit.xml
  fi
notifications:
  email: false
  slack:
    rooms:
      secure: pxvoASZHk6TGDqhLTVGQ5v8oEncLMOtpNKqKIHwV9pNoSorsxEMKHx7uimnhnUMTE4Tpu+0/cxsh+8jizPYJRsk1PR3alQHjbwpq2zdHeG6gUAct6n5tLhn0yeELvv6hqogmqJf2wV90RoKJyNQkv6a9FPoYZbJ+m4euP9h2JqScQZpJzkYF2WPOj8C/PQzq1OpQ5Eu0ig522U0mLDrkLvFOYamIaWE3rjKLnoNgmn3iHV4XVRe7S7CHND1fpsZAKj3Quozsccuye1TjmwgWrVO1FQAC2lzpF3HiH5UPuDIg48mlHwHbV/dPq/c/8v1Kd6NINsjkdFyRz3T9V3e9lvkSXh4GCkei9/Ta+KdrIzVMY1BVwcGygVXw4u3jROX27Dl3S6eJWD8UuE65nBHFJZCWjbhzrKIpep+ZIy6MRi4LKtOKWyEDUaL2brI9t2z1W1z6qkLHTccf89ZluMfv9vIw+FVzs3eqQ/PlCKZzola1PsrXY9Dm2GsTer8xYOBSODSjd7T0VrAJVhSHCq53xpYWlszcgX9dtrsT6L6QcPMRxjoOttsTNhaUYk/19HcYbYzPxB0J2WP/9IkVWlDc2Z4uD5Lvb30h1aOCfg2/L2LpERcgHItRrwxBotx+BHWD/q4WUIHgD/BCmAO3nv0msRZn3+KbD4+icEsCyCWenTg=
    on_success: change
    on_failure: always
